### ISSUE TITLE
报bug

### ISSUE THREAD

**Issue by WinnerDuDu** [Sunnshino/sunui-upimg#2]
批量上传图片，所有的进度显示一样。
upload_file_server方法下面的
`for (let i = 0, len = _this.upload_picture_list.length; i < len; i++) {
					upload_picture_list[i]['upload_percent'] = progress.progress;
				}`
改为
`upload_picture_list[j]['upload_percent'] = progress.progress;`
即可

**Comment by Sunnshino** [comment]
这个你确定吗？ 上传时一张一张的，所以监控也是按照上传长度来循环的.

**Comment by WinnerDuDu** [comment]
> 这个你确定吗？ 上传时一张一张的，所以监控也是按照上传长度来循环的.

我用的H5测试的，上传9张5M左右的图片，进度显示确实是同步的，改为下面的代码就实现了单张图片进度显示。

**Comment by Sunnshino** [comment]
这个是属于七牛云的，我试试吧，多谢



------------------ Original ------------------

**Comment by tangniyuqi** [comment]
今天我也偶尔出现此情况

**Comment by Sunnshino** [comment]
以前的上传图片bug较多，建议使用简便版(sunui-upimg.vue)再导入七牛上传图片的sdk。
